
services:
  aspnetcoresocialsurvey:
    depends_on:
    - mssql
    image: aspnetcoresocialsurvey:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=mssql;Database=SocialSurvey;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"
    networks:
      - mynetwork
    entrypoint: 
        /bin/bash -c "dotnet ef database update && dotnet SocialSurvey.dll"

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
